In [23]:
import numpy as np

Question:1
Convert a 1D array to a 2D array with 2 rows?

In [24]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
array = array.reshape(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Question 2: How to stack two arrays vertically?
Desired Output::
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

In [25]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])
array = np.vstack((a,b))
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q3: How to stack two arrays horizontally?

In [26]:
arr = np.hstack((a,b))
arr

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Question:4
How to convert an array of arrays into a flat 1d array?

In [27]:
array = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = array.ravel()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Question:5
How to Convert higher dimension into one dimension?

In [28]:
arr = np.arange(15).reshape((5, 3))
arr = arr.flatten()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
arr2 = arr.reshape(5,-1)
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Question:7
Create 5x5 an array and find the square of an array?

In [30]:
s = np.random.randint(10, size=(5,5))
s

array([[7, 0, 0, 7, 3],
       [3, 9, 1, 4, 6],
       [9, 0, 1, 8, 2],
       [5, 8, 6, 5, 8],
       [9, 5, 2, 8, 1]])

In [31]:
sq = np.sqrt(s)
sq

array([[2.64575131, 0.        , 0.        , 2.64575131, 1.73205081],
       [1.73205081, 3.        , 1.        , 2.        , 2.44948974],
       [3.        , 0.        , 1.        , 2.82842712, 1.41421356],
       [2.23606798, 2.82842712, 2.44948974, 2.23606798, 2.82842712],
       [3.        , 2.23606798, 1.41421356, 2.82842712, 1.        ]])

Question:8
Create 5x6 an array and find the mean?

In [32]:
m = np.random.randint(50, size=(5,6))
m

array([[19,  2, 29, 15, 31, 36],
       [47,  5, 10, 23, 15, 44],
       [38, 24, 13, 36, 17, 21],
       [44, 35,  5, 41, 45, 13],
       [ 0, 25, 19, 18, 33, 10]])

In [33]:
mn = np.mean(m)
mn

23.766666666666666

Question:9
Find the standard deviation of the previous array in Q8?¶

In [34]:
sd = np.std(m)
sd

13.590887470000707

Question:10
Find the median of the previous array in Q8?

In [35]:
mdn = np.median(m)
mdn

22.0

Question:11
Find the transpose of the previous array in Q8?

In [36]:
tr = m.T
tr

array([[19, 47, 38, 44,  0],
       [ 2,  5, 24, 35, 25],
       [29, 10, 13,  5, 19],
       [15, 23, 36, 41, 18],
       [31, 15, 17, 45, 33],
       [36, 44, 21, 13, 10]])

Question:12
Create a 4x4 an array and find the sum of diagonal elements?

In [37]:
m = np.random.randint(10, size=(4,4))
m

array([[6, 5, 4, 3],
       [5, 7, 8, 4],
       [7, 1, 1, 1],
       [4, 5, 6, 8]])

In [38]:
sumd = np.trace(m)
sumd

22

Question:13
Find the determinant of the previous array in Q12?

In [39]:
import numpy.linalg as nl

In [40]:
dtr = nl.det(m)
dtr

372.99999999999983

Question:14
Find the 5th and 95th percentile of an array?

In [41]:
array = np.random.rand(5,5)
array

array([[0.35987459, 0.21281766, 0.26360199, 0.43079862, 0.90058225],
       [0.66603714, 0.13057852, 0.3494048 , 0.68186667, 0.66979441],
       [0.52440754, 0.62436876, 0.17052303, 0.02233285, 0.67947195],
       [0.81949991, 0.92597241, 0.76497706, 0.26055198, 0.10431859],
       [0.42538327, 0.81044408, 0.95134891, 0.64059604, 0.04823789]])

In [42]:
#5th Percentile
p5 = np.percentile(array,5)
p5

0.059454027412701796

In [43]:
#95th Percentile
p95 = np.percentile(array,95)
p95

0.9208943754973283

Question:15
How to find if a given array has any null values?

In [44]:
np.isnan([np.nan,5,6,5,8])

array([ True, False, False, False, False])