Import the numpy package under the name np

In [1]:
import numpy as np

Create a null vector of size 10

In [2]:
x=np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create a vector with values ranging from 10 to 49

In [3]:
y=np.arange(10,49)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Find the shape of previous array in question 3

In [4]:
np.shape(y)

(39,)

Print the type of the previous array in question 3

In [5]:
y.dtype

dtype('int32')

Print the numpy version and the configuration

In [6]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mustafa.zaidi/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/mustafa.zaidi/AppData/Local/Continuum/anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mustafa.zaidi/AppData/Local/Continuum/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include'

Print the dimension of the array in question 3

In [7]:
y.shape

(39,)

Create a boolean array with all the True values

In [8]:
x<1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Create a two dimensional array

In [9]:
z=np.array([(1,2,3,4),(5,6,7,8)])
z

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Create a three dimensional array

In [10]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Reverse a vector (first element becomes last)

In [11]:
y[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

Create a null vector of size 10 but the fifth value which is 1

In [12]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Create a 3x3 identity matrix

In [13]:
p=np.eye(3)
p

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Convert the data type of the given array from int to float

In [14]:
arr = np.array([1, 2, 3, 4, 5])
f=arr.astype(float)
f

array([1., 2., 3., 4., 5.])

Multiply arr1 with arr2

In [15]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
multi=arr1*arr2
multi

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
print("Element wise")
arr1==arr2


Element wise


array([[False, False, False],
       [False, False, False]])

In [17]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])
print("Array wise")
np.array_equal(arr1,arr2)

Array wise


False

Extract all odd numbers from arr with values(0-9)

In [18]:
q=np.arange(1,10,2)
q

array([1, 3, 5, 7, 9])

Replace all odd numbers to -1 from previous array

In [19]:
q[:]=-1
q

array([-1, -1, -1, -1, -1])

arr = np.arange(10)
Replace the values of indexes 5,6,7 and 8 to 12

In [20]:
arr=np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

Create a 2d array with 1 on the border and 0 inside

In [21]:
p=np.ones((3,3))
p[1:-1,1:-1]=0
p

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [22]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [23]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
arr3d[0,0]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [24]:
arr2d=np.array([(0,1,2,3,4),(5,6,7,8,9)])
arr2d[0]

array([0, 1, 2, 3, 4])

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [25]:
arr2d=np.array([(0,1,2,3,4),(5,6,7,8,9)])
arr2d[1,2]

7

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [26]:
arr2d[:2,2]

array([2, 7])

Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
v=np.random.randn(10,10)
v

array([[ 0.683565  , -0.78119242,  0.11587061,  2.67292272, -0.5708101 ,
         0.9388656 ,  0.43045624,  0.38445674, -0.78873613,  0.39004747],
       [ 1.18450545, -1.65378272,  0.79026397, -1.10203996,  1.60082677,
        -0.77314673,  0.83234579, -0.86533329,  2.61133472, -0.45925593],
       [-0.22980981, -0.96200361, -0.68633775, -0.27315621,  0.80913146,
        -0.1468899 , -1.66066517, -0.89658367, -1.52038622, -0.10033887],
       [-0.36794304, -1.39285527,  0.33661334, -1.52518402, -1.77822836,
         0.94114577,  0.51944925, -0.59010851, -0.84917564, -0.1566801 ],
       [ 0.58105112, -0.31156228,  1.11346509,  0.97105995, -0.14046129,
         0.76235922,  0.48685102,  0.39766926, -0.79657831, -2.06377105],
       [-0.29313333,  0.14135467, -0.75999135,  0.21868856,  0.43321278,
        -0.79700756, -0.35441396, -0.79605287,  0.31007607, -0.08227813],
       [ 0.54983715, -0.45225725, -0.94420921,  0.12737172,  0.92609408,
        -0.97680936, -0.69112446, -0.12731425

In [28]:
v.min()

-2.063771053693335

In [29]:
v.max()

2.6729227182408035

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=a[a==b]
c

array([2, 2, 4, 4])

Find the positions where elements of a and b match

In [31]:
np.searchsorted(a,c)

array([1, 1, 5, 5], dtype=int32)

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)
Find all the values from array data where the values from array names are not equal to Will

In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data

array([[-1.39586954,  0.62693064,  0.1980328 , -1.24743099],
       [-0.64763498, -0.46374725,  0.81528216, -0.25882404],
       [ 2.5033072 ,  1.99013262, -0.05381365,  0.50484523],
       [ 0.07395393,  0.07319519, -0.20367813, -0.01360989],
       [-1.78335598, -0.0157261 , -0.15059602, -1.28070483],
       [ 0.15221904, -3.12619132, -1.89291844,  0.10125773],
       [-0.25254646, -1.03713233,  0.22520388, -0.14173187]])

In [33]:
names != 'Will'

array([ True,  True, False,  True, False,  True,  True])

Find all the values from array data where the values from array names are not equal to Will and Joe

In [34]:
mask = (names != 'Will') & (names != 'Joe')
mask

array([ True, False, False,  True, False, False, False])

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [35]:
arr = np.empty((5,3))
arr

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 2.44029516e-312]])

Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [36]:
arr2 = np.empty((2,2,4))
arr2

array([[[ 2.63178491e-310,  1.63002224e-070,  3.14521614e+161,
          8.87696997e+247],
        [-2.70025505e+108,  5.19723188e-314,  1.58456374e+029,
          4.28354915e-321]],

       [[ 3.25938554e-311,  1.39267373e-304,  2.21672182e-301,
          5.83450858e-302],
        [ 3.82447961e-297,  2.50593676e-292,  2.49328349e-306,
          5.01477874e-292]]])

Swap axes of the array you created in Question 32

In [37]:
arr3= arr2.T
arr3

array([[[ 2.63178491e-310,  3.25938554e-311],
        [-2.70025505e+108,  3.82447961e-297]],

       [[ 1.63002224e-070,  1.39267373e-304],
        [ 5.19723188e-314,  2.50593676e-292]],

       [[ 3.14521614e+161,  2.21672182e-301],
        [ 1.58456374e+029,  2.49328349e-306]],

       [[ 8.87696997e+247,  5.83450858e-302],
        [ 4.28354915e-321,  5.01477874e-292]]])

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [38]:
arr4 = np.array([3,0.2,2,5,7,0.1,0.1,8,4,0.23])
arr5=np.sqrt(arr4)
arr5

array([1.73205081, 0.4472136 , 1.41421356, 2.23606798, 2.64575131,
       0.31622777, 0.31622777, 2.82842712, 2.        , 0.47958315])

In [39]:
arr5<0.5

array([False,  True, False, False, False,  True,  True, False, False,
        True])

In [40]:
np.where(arr5<0.5,0,arr5)

array([1.73205081, 0.        , 1.41421356, 2.23606798, 2.64575131,
       0.        , 0.        , 2.82842712, 2.        , 0.        ])

Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [41]:
a = np.random.rand(12)
a

array([0.51419791, 0.04685838, 0.79410719, 0.49748615, 0.01087132,
       0.75794504, 0.48295396, 0.3120105 , 0.69246442, 0.30395861,
       0.39911181, 0.22176763])

In [42]:
b = np.random.rand(12)
b

array([0.94838631, 0.43866287, 0.35592118, 0.7743468 , 0.61593026,
       0.70341286, 0.63785078, 0.77764745, 0.55162763, 0.25650425,
       0.45765027, 0.86420133])

In [43]:
np.maximum(a,b)

array([0.94838631, 0.43866287, 0.79410719, 0.7743468 , 0.61593026,
       0.75794504, 0.63785078, 0.77764745, 0.69246442, 0.30395861,
       0.45765027, 0.86420133])

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
Find the unique names and sort them out!

In [44]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique = np.unique(names)
unique

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [45]:
np.sort(unique)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])
From array a remove all items present in array b

In [46]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])

In [47]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray[:,1]=newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])
Find the dot product of the above two matrix

In [48]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

Generate a matrix of 20 random values and find its cumulative sum

In [49]:
cs = np.random.rand(20)
cs

array([0.12101219, 0.13503171, 0.90054557, 0.970463  , 0.47187805,
       0.8122549 , 0.17365003, 0.26891264, 0.90990213, 0.97388878,
       0.99977245, 0.05858154, 0.48435002, 0.00391303, 0.48937984,
       0.92588042, 0.73338707, 0.01904191, 0.30793567, 0.99103474])

In [50]:
np.cumsum(cs)

array([ 0.12101219,  0.2560439 ,  1.15658946,  2.12705246,  2.59893051,
        3.41118541,  3.58483544,  3.85374808,  4.76365021,  5.73753898,
        6.73731143,  6.79589297,  7.28024299,  7.28415601,  7.77353585,
        8.69941627,  9.43280334,  9.45184526,  9.75978093, 10.75081567])